version: '3.1'
services:

  nginx:
    links:
      - pgadmin:pgadmin
    image: "nginx:1.13.12"
    ports:
      - "80:80"
    volumes:
      - ./nginxServers/server:/etc/nginx/conf.d/default.conf
      
  # pgadmin4 for pgbouncer.
  pgadmin4-master:
    image: fenglc/pgadmin4
    ports:
      - 5050:5050
    links:
      - postgres:postgres
    environment:
      DEFAULT_USER: pgbouncer_database
      DEFAULT_PASSWORD: 12345678
    networks:
      - swarm1
    
  # Postgres database.
  postgres:
    image: postgres:9.6.5 
    environment:
      POSTGRES_USER: postgres     # define credentials
      POSTGRES_PASSWORD: postgres # define credentials
      POSTGRES_DB: postgres       # define database
    ports:
      - 5432:5432   # Postgres port
    networks:
      - swarm1
                     
  # Postgres database.
  pgbouncer:
    image: brainsam/pgbouncer:1.7.2
    environment:
      DB_HOST: postgres
      DB_USER: postgres           # define credentials
      DB_PASSWORD: postgres       # define credentials
      DB_port: 5432               # define database
    links:
      - postgres:postgres
    ports:
      - 6432:6432
    networks:
      - swarm1                 # PgBouncer port

networks:
  swarm1:
