version: '3.1'
services:
  pgbouncer:
    image: "docker.io/pushpendersingh/pgbouncer_update1"
    ports: 
      - 5439:5439
    environment:
     DB_HOST: "localhost"
     DB_USER: "postgres"
     DB_PORT: "5432"
     DB_PASSWORD: "postgres"
     LISTEN_PORT: "5439"
    networks:
      - db_nw        

networks:
  db_nw:
    external:
      name: db_nw
