version: '3'                                                                                                                            
services:
  flaskapp1:
    image: pushpendersingh/flask_super 
    env_file:
      - env_file
    environment:
      build_env: production
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "5090:5090"
    volumes:
      - .:/opt/services/flaskapp/src
    networks:
      - db_nw
      - web_nw

networks:
  db_nw:
    external:
      name: db_nw
  web_nw:
    external:
      name: web_nw

