version: '3'
services:
  logspout:
    image: gliderlabs/logspout:latest
    networks:
      - db_nw
      - web_nw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      syslog://syslog-a.logdna.com:39149
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.20'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M

networks:
  db_nw:
    external:
      name: db_nw
  web_nw:
    external:
      name: web_nw
