version: "3"
networks:
  swarm1:
services:
  logspout:
    image: gliderlabs/logspout:latest
    networks:
      - swarm1
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      syslog://syslog-a.logdna.com:26496
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.20'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
  
    