- name: Join Swarm Cluster as a Worker
  command: docker swarm join --token {{ token }} {{ manager }}:2377
  ignore_errors: yes
  register: worker

- name: Show Results
  debug: var=worker.stdout

- name: Show Errors
  debug: var=worker.stderr
