---
 - name: Install Python
   hosts: managers:workers
   become: true
   gather_facts: False
   roles:
    - python

 - name: Init Swarm cluster
   hosts: managers
   become: true
   gather_facts: False
   roles:
    - swarm-init

 - name: Join Swarm cluster
   hosts: workers
   become: true
   gather_facts: False
   vars:
    token: "{{ hostvars[groups['managers'][0]]['worker_token']['stdout'] }}"
    manager: "{{ hostvars[groups['managers'][0]]['inventory_hostname'] }}"
   roles:
    - swarm-join
